
-- vim.g.tabby_server_url = "http://127.0.0.1:9090"
-- vim.g.tabby_node_binary = vim.fn.expand("~/.nvm/versions/node/v20.10.0/bin/node")
-- vim.g.tabby_trigger_mode = "manual"
-- vim.g.tabby_keybinding_accept = "<Tab>"
-- vim.g.tabby_keybinding_trigger_or_dismiss = "<C-l>"

return {
  {"github/copilot.vim"}
  -- {
  --   "TabbyML/vim-tabby",
  --   cmd = "Tabby",
  --   event = { "BufReadPost", "BufNewFile" },
  --   lazy = false, -- FIXME: cannot make it lazyload
  --   dependencies = {
  --     "neovim/nvim-lspconfig",
  --   },
  --   init = function()
  --     -- vim.g.tabby_server_url = "http://127.0.0.1:9090"
  --     vim.g.tabby_node_binary = vim.fn.expand("~/.nvm/versions/node/v20.10.0/bin/node")
      
  --     vim.g.tabby_agent_start_command = {"npx", "tabby-agent", "--stdio"}
  --     vim.g.tabby_inline_completion_trigger = "manual"

  --     -- vim.g.tabby_trigger_mode = "manual"
  --     vim.g.tabby_inline_completion_keybinding_accept = "<Tab>" 
  --     vim.g.tabby_inline_completion_keybinding_trigger_or_dismiss = '<C-\\>'
  --   end,
  --   keys = {
  --     {
  --       "<leader>ta",
  --       function()
  --         if vim.g.tabby_inline_completion_trigger == "manual" then
  --           vim.g.tabby_inline_completion_trigger = "auto"
  --         else
  --           vim.g.tabby_inline_completion_trigger = "manual"
  --         end
  --       end,
  --       desc = "Tabby toggle",
  --     },
  --   },
  -- },

  -- https://github.com/yetone/avante.nvim
  -- https://github.com/olimorris/codecompanion.nvim
  -- https://github.com/paul-gauthier/aider
  -- {
  --   "yetone/avante.nvim",
  --   event = "VeryLazy",
  --   lazy = false,
  --   version = false, -- set this if you want to always pull the latest change
  --   opts = {
  --     -- provider = "claude", -- Only recommend using Claude
  --     -- auto_suggestions_provider = "claude",
  --     -- provider = "deepseekcoder", -- Only recommend using Claude
  --     -- auto_suggestions_provider = "deepseekcoder",

  --     provider = "deepseekcoder",
  --     auto_suggestions_provider = "deepseekcoder",
      
  --     claude = {
  --       endpoint = "https://api.anthropic.com",
  --       model = "claude-3-5-sonnet-20240620",
  --       timeout = 30000, -- Timeout in milliseconds
  --       temperature = 0,
  --       max_tokens = 8000,
  --       ["local"] = false,
  --     },
  --     vendors = {      
  --         ---@type AvanteProvider
  --         ollama_deepseekcoder2 = {
  --           ["local"] = true,
  --           endpoint = "grad7.mywire.org:11434",
  --           model = "deepseek-coder-v2:latest",
  --           parse_curl_args = function(opts, code_opts)
  --             return {
  --               url = opts.endpoint .. "/api/chat",
  --               headers = {
  --                 ["Accept"] = "application/json",
  --                 ["Content-Type"] = "application/json",
  --               },
  --               body = {
  --                 model = opts.model,
  --                 messages = require("avante.providers").copilot.parse_message(code_opts), -- you can make your own message, but this is very advanced
  --                 max_tokens = 2048,
  --                 stream = true,
  --               },
  --             }
  --           end,
  --           parse_response_data = function(data_stream, event_state, opts)
  --             require("avante.providers").openai.parse_response(data_stream, event_state, opts)
  --           end,
  --         },
  --         ollama_mistral = {
  --           ["local"] = true,
  --           endpoint = "grad7.mywire.org:11434",
  --           model = "mistral:latest",
  --           parse_curl_args = function(opts, code_opts)
  --             return {
  --               url = opts.endpoint .. "/api/chat",
  --               headers = {
  --                 ["Accept"] = "application/json",
  --                 ["Content-Type"] = "application/json",
  --               },
  --               body = {
  --                 model = opts.model,
  --                 messages = require("avante.providers").copilot.parse_message(code_opts), -- you can make your own message, but this is very advanced
  --                 max_tokens = 2048,
  --                 stream = true,
  --               },
  --             }
  --           end,
  --           parse_response_data = function(data_stream, event_state, opts)
  --             require("avante.providers").openai.parse_response(data_stream, event_state, opts)
  --           end,
  --         },
  --         deepseekcoder2 = {
  --           ["local"] = true,
  --           endpoint = "127.0.0.1:9094/v1",
  --           model = "deepseekcoder2",
  --           parse_curl_args = function(opts, code_opts)
  --             return {
  --               url = opts.endpoint .. "/chat/completions",
  --               headers = {
  --                 ["Accept"] = "application/json",
  --                 ["Content-Type"] = "application/json",
  --               },
  --               body = {
  --                 model = opts.model,
  --                 messages = require("avante.providers").copilot.parse_message(code_opts), -- you can make your own message, but this is very advanced
  --                 max_tokens = 2048,
  --                 stream = true,
  --               },
  --             }
  --           end,
  --           parse_response_data = function(data_stream, event_state, opts)
  --             require("avante.providers").openai.parse_response(data_stream, event_state, opts)
  --           end,
  --         },
  --         deepseekcoder = {
  --           ["local"] = true,
  --           endpoint = "127.0.0.1:9092/v1",
  --           model = "deepseekcoder",
  --           parse_curl_args = function(opts, code_opts)
  --             return {
  --               url = opts.endpoint .. "/chat/completions",
  --               headers = {
  --                 ["Accept"] = "application/json",
  --                 ["Content-Type"] = "application/json",
  --               },
  --               body = {
  --                 model = opts.model,
  --                 messages = require("avante.providers").copilot.parse_message(code_opts), -- you can make your own message, but this is very advanced
  --                 max_tokens = 2048,
  --                 stream = true,
  --               },
  --             }
  --           end,
  --           parse_response_data = function(data_stream, event_state, opts)
  --             require("avante.providers").openai.parse_response(data_stream, event_state, opts)
  --           end,
  --         },
  --         queen = {
  --           ["local"] = true,
  --           endpoint = "127.0.0.1:9091/v1",
  --           model = "queen",
  --           parse_curl_args = function(opts, code_opts)
  --             return {
  --               url = opts.endpoint .. "/chat/completions",
  --               headers = {
  --                 ["Accept"] = "application/json",
  --                 ["Content-Type"] = "application/json",
  --               },
  --               body = {
  --                 model = opts.model,
  --                 messages = require("avante.providers").copilot.parse_message(code_opts), -- you can make your own message, but this is very advanced
  --                 max_tokens = 2048,
  --                 stream = true,
  --               },
  --             }
  --           end,
  --           parse_response_data = function(data_stream, event_state, opts)
  --             require("avante.providers").openai.parse_response(data_stream, event_state, opts)
  --           end,
  --         },
  --         mistral = {
  --           ["local"] = true,
  --           endpoint = "127.0.0.1:9093/v1",
  --           model = "mistral",
  --           parse_curl_args = function(opts, code_opts)
  --             return {
  --               url = opts.endpoint .. "/chat/completions",
  --               headers = {
  --                 ["Accept"] = "application/json",
  --                 ["Content-Type"] = "application/json",
  --               },
  --               body = {
  --                 model = opts.model,
  --                 messages = require("avante.providers").copilot.parse_message(code_opts), -- you can make your own message, but this is very advanced
  --                 max_tokens = 2048,
  --                 stream = true,
  --               },
  --             }
  --           end,
  --           parse_response_data = function(data_stream, event_state, opts)
  --             require("avante.providers").openai.parse_response(data_stream, event_state, opts)
  --           end,
  --         },
  --     },
  --   },
  --   -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
  --   build = "make",
  --   -- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
  --   dependencies = {
  --     "nvim-treesitter/nvim-treesitter",
  --     "stevearc/dressing.nvim",
  --     "nvim-lua/plenary.nvim",
  --     "MunifTanjim/nui.nvim",
  --     --- The below dependencies are optional,
  --     "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
  --     {
  --       -- support for image pasting
  --       "HakonHarnes/img-clip.nvim",
  --       event = "VeryLazy",
  --       opts = {
  --         -- recommended settings
  --         default = {
  --           embed_image_as_base64 = false,
  --           prompt_for_file_name = false,
  --           drag_and_drop = {
  --             insert_mode = true,
  --           },
  --           -- required for Windows users
  --           use_absolute_path = true,
  --         },
  --       },
  --     },
  --     {
  --       -- Make sure to set this up properly if you have lazy=true
  --       'MeanderingProgrammer/render-markdown.nvim',
  --       opts = {
  --         file_types = { "markdown", "Avante" },
  --       },
  --       ft = { "markdown", "Avante" },
  --     },
  --   },

  --   -- https://github.com/yetone/avante.nvim/wiki
  -- }
}
